# Generated by Django 3.0.7 on 2020-06-23 16:46

from django.db import migrations, models
import django.utils.timezone
import xblogapps.cores.utils
import xblogapps.users.managers.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('avatar', models.ImageField(blank=True, upload_to=xblogapps.cores.utils.ImageHandler.upload_handler, verbose_name='Profile picture')),
                ('slug', models.SlugField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='First name')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('about', models.TextField(blank=True, verbose_name='About Me')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.URLField(blank=True, default='https://')),
                ('github', models.URLField(blank=True, default='https://github.com/')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/@')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', xblogapps.users.managers.user.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'username'), name='user_unique_email_username'),
        ),
    ]
